<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;

class File extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'extension', 'file_path'];

    public static function upload(UploadedFile $file) {
        $newFile = new File;
        $fileName = Str::random() . '_' . $file->getClientOriginalName();
        $filePath = $file->storeAs('/uploads/user_avatar/', $fileName, 'public');
        $newFile->fill([
            'name' => $file->getClientOriginalName(),
            'extension' => $file->clientExtension(),
            'file_path' => '/uploads/user_avatar/' . $fileName,
        ]);
        $newFile->save();

        return $newFile;
    }

    public function delete()
    {
        unlink(storage_path('app/public' . $this->file_path));
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
